### PR TITLE
Feature/turkish lbx

### PR DESCRIPTION
**Pull request by abdulkerimgok**
I added my translations (turkish .lbx file) and the modified version of the localization keys to the lbx folder as per developers suggestion. 

You could remove your test-turkish-lbx if you'd like. 

I am able to compile the pdf with localization keys without the bibliography. There are only a couple of strings that are undefined for some reason. 

The bibliography is not compiling probably because of the date/time extras. I tried a couple of things, but no success so far. 

So I am going to write to the developers and they'll hopefully fix both problems.

### CODE REVIEW

**Comment by bariserkusgit** [comment]
👍 

@abdulkerimgok This is a major contrubition indeed. Thanks for the hard work. I will review it and let you know.

One thing I observed is that developers suggests to use ASCII characters for non-standard characters (e.g. accents). You used the LaTeX shorthands for those. What do you think?

**Comment by abdulkerimgok** [comment]
I knew about the ASCII characters, but when I first did that there were some problems. 

And when I looked at the german.lbx, they used the same convention for accents so I left it like that for now. If that will be a huge problem, I can fix it.

**Comment by abdulkerimgok** [comment]
For the location of the localization key file, here is a excerpt from the readme file of the main branch. So that's why I included that tex file in the lbx folder. 

"To debug or verify that a translation is complete, copy doc/latex/biblatex/examples/03-localization-keys.tex to tex/latex/biblatex/lbx. Edit 03-localization-keys.tex so Babel (and hence Biblatex) uses the language you are translating. Compiling the file will warn you about missing strings, and looking at the generated file will help you to proofread your translation."

**Comment by bariserkusgit** [comment]
> I knew about the ASCII characters, but when I first did that there were some problems.
> 
> And when I looked at the german.lbx, they used the same convention for accents so I left it like that for now. If that will be a huge problem, I can fix it.

I see. I think we can as to the developers. What kind of problems did you have? Maybe we can solve it.

**Comment by abdulkerimgok** [comment]
I had minor edit in the localization key file. I don't know if I need to request a pull after each commit. 

Not an expert with the git workflow.

**Comment by bariserkusgit** [comment]
> For the location of the localization key file, here is a excerpt from the readme file of the main branch. So that's why I included that tex file in the lbx folder.
> 
> "To debug or verify that a translation is complete, copy doc/latex/biblatex/examples/03-localization-keys.tex to tex/latex/biblatex/lbx. Edit 03-localization-keys.tex so Babel (and hence Biblatex) uses the language you are translating. Compiling the file will warn you about missing strings, and looking at the generated file will help you to proofread your translation."

Yes. I remember this one. I can live with that. But in the final push, this file should be in its original folder I guess.

I will test your lbx file and let you know. Thanks again!!!

**Comment by abdulkerimgok** [comment]
when testing, comment out /printbibliography at the end of localization key, otherwise you'll get an error for date extras. 

please check the pdf and translations and let me know if any of the translations don't make any sense.

**Comment by abdulkerimgok** [comment]
I also added a comment/questions to your original issue message for developers. Please see that as well if you haven't yet. And add your own if have any.

**Comment by bariserkusgit** [comment]
> I had minor edit in the localization key file. I don't know if I need to request a pull after each commit.
> 
> Not an expert with the git workflow.

No need. Just keep it on your side. You can request a pull after you collect all the changes.

**Comment by abdulkerimgok** [comment]
I did fix the csquote package error with defining quotation marks for turkish as it not defined in that package by default. 

The problem with dates still remains. I checked everything, but couldn't figure out why it's happening. 

If you force compile with date errors, it prints the word "year" in the bibliography. 

The other problem is the reversed grammer of turkish and that I believe has to be dealt by the developers.    

Capture

**Pull request closed without merging**
